"""
ai_analyzer.py — Google Gemini-powered market analysis
"""

import asyncio
import logging
from typing import Any

from g4f.client import AsyncClient
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("trade_api.ai_analyzer")

SYSTEM_PROMPT = """You are a senior trade analyst specialising in India's import/export markets.
Your task is to produce a structured, data-rich markdown report on current
trade opportunities for a given sector in India.

Always respond with valid Markdown only — no preamble outside the document.

The report MUST contain exactly these sections:

# 🇮🇳 Trade Opportunities Report: {SECTOR}

## 1. Executive Summary
3-4 sentence overview of the sector's current position in Indian trade.

## 2. Market Overview
- Current market size (USD) and CAGR
- Key government initiatives / policies (PLI, Make in India, etc.)
- Regulatory environment

## 3. Export Opportunities
| Product / Sub-sector | Key Destination Markets | Opportunity Size | Growth Driver |
|---|---|---|---|
(at least 4 rows)

## 4. Import Opportunities
| Product / Sub-sector | Source Countries | Strategic Reason |
|---|---|---|
(at least 3 rows)

## 5. Key Trends & Drivers
5-7 bullet points of current trends.

## 6. Risks & Challenges
3-5 bullet points of key risks.

## 7. Top Companies & Key Players
| Company | Role | Notable Activity |
|---|---|---|
(at least 5 rows)

## 8. Investment & Funding Landscape
Recent FDI inflows, notable deals, government incentives.

## 9. Actionable Trade Recommendations
4-6 numbered concrete steps for businesses.

## 10. Data Sources & References
Bullet list of sources used (URLs from context or DGFT, IBEF, MoC, RBI, etc.)

---
*Report generated by Trade Opportunities API | Data as of {DATE}*""".strip()


class AIAnalyzer:
    """Wraps Google Gemini to produce structured markdown trade analysis reports."""

    def __init__(self):
        self._client = AsyncClient()
        logger.info("G4F client initialised.")

    async def analyze(self, sector: str, market_data: dict[str, Any]) -> str:

        prompt = self._build_prompt(sector, market_data)
        loop = asyncio.get_event_loop()

        try:
            response = await self._client.chat.completions.create(
                model="gpt-4",
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content
        except Exception as exc:
            logger.error("G4F API error: %s", exc)
            raise

    def _build_prompt(self, sector: str, market_data: dict[str, Any]) -> str:
        from datetime import date

        articles = market_data.get("articles", [])
        note = market_data.get("note", "")

        context_lines = []
        for i, art in enumerate(articles[:15], start=1):
            title = art.get("title", "No title")
            body = art.get("body", art.get("snippet", ""))[:400]
            url = art.get("href", "")
            context_lines.append(f"{i}. **{title}**\n   {body}\n   Source: {url}")

        context_block = (
            "\n\n".join(context_lines) if context_lines
            else f"No live articles collected. {note}"
        )

        system = SYSTEM_PROMPT.replace("{SECTOR}", sector.title()).replace(
            "{DATE}", date.today().strftime("%B %Y")
        )

        return (
            f"{system}\n\n---\n## Collected Market Context\n\n"
            f"{context_block}\n\n---\n"
            f"Now generate the full trade opportunities report for the "
            f"**{sector.title()}** sector in India."
        )

    def _mock_report(self, sector: str) -> str:
        from datetime import date
        return f"""# 🇮🇳 Trade Opportunities Report: {sector.title()}

> ⚠️ **Demo Mode** — `GEMINI_API_KEY` is not configured.
> Set the environment variable to receive a live AI-generated report.

## 1. Executive Summary
This is a placeholder report for the **{sector.title()}** sector.
Configure `GEMINI_API_KEY` in your `.env` file to enable AI-powered analysis.

## 2. Market Overview
- Market size: _data requires live AI analysis_
- CAGR: _data requires live AI analysis_

## 3. Export Opportunities
| Product / Sub-sector | Key Destination Markets | Opportunity Size | Growth Driver |
|---|---|---|---|
| _Configure Gemini_ | — | — | — |

## 4. Import Opportunities
| Product / Sub-sector | Source Countries | Strategic Reason |
|---|---|---|
| _Configure Gemini_ | — | — |

## 5. Key Trends & Drivers
- Set `GEMINI_API_KEY` to see live trends.

## 6. Risks & Challenges
- Set `GEMINI_API_KEY` to see risks.

## 7. Top Companies & Key Players
| Company | Role | Notable Activity |
|---|---|---|
| _Configure Gemini_ | — | — |

## 8. Investment & Funding Landscape
_Configure Gemini API to see real analysis._

## 9. Actionable Trade Recommendations
1. Configure `GEMINI_API_KEY` in `.env`
2. Restart the server
3. Retry this endpoint

## 10. Data Sources & References
- DGFT (Directorate General of Foreign Trade)
- IBEF (India Brand Equity Foundation)
- Ministry of Commerce and Industry

---
*Report generated by Trade Opportunities API | {date.today().strftime("%B %Y")}*
"""
